# Generated by Django 3.2.16 on 2023-11-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256, verbose_name='имя пользователя')),
                ('email', models.EmailField(max_length=256, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Телефон')),
                ('data_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'форма регистрации',
                'verbose_name_plural': 'Форма Регистрации',
            },
        ),
    ]
