# Generated by Django 3.2.16 on 2023-11-17 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myforms',
            options={'verbose_name': 'форма регистрации', 'verbose_name_plural': 'Форма Регистрации'},
        ),
    ]
